export const CONFIG = {
  world: {
    sizeX: 320,
    sizeZ: 320,
    height: 96,
    segments: 384,
    seed: 20260924,
  },
  render: {
    maxPixelRatio: 1.5,
  },
  graphics: {
    quality: 'high',
    toneMappingExposure: 0.94,
    shadows: {
      enabled: true,
      mapSize: 2048,
      extent: 70,
      bias: -0.0002,
      normalBias: 0.045,
    },
    ssao: {
      enabled: true,
      kernelSize: 16,
      kernelRadius: 8,
      minDistance: 0.0022,
      maxDistance: 0.075,
    },
    bloom: {
      strength: 0.5,
      radius: 0.72,
      threshold: 0.72,
    },
    godRays: {
      enabled: true,
      density: 0.88,
      decay: 0.95,
      weight: 0.3,
      exposure: 0.26,
      samples: 28,
    },
    colorGrade: {
      vignette: 0.24,
      grain: 0.022,
      chromatic: 0.0014,
      saturation: 1.16,
      contrast: 1.05,
      warmth: 0.1,
    },
    particles: {
      motes: 550,
      fireflies: 150,
      leaves: 320,
      volume: 80,
    },
    water: {
      waveHeight: 0.09,
    },
    wind: {
      strength: 1,
      gust: 0.4,
    },
    grass: {
      count: 14000,
      radius: 150,
    },
  },
  player: {
    width: 0.6,
    height: 1.8,
    eyeHeight: 1.62,
    walkSpeed: 6.2,
    sprintSpeed: 10.2,
    swimSpeed: 3.6,
    acceleration: 46,
    friction: 14,
    airControl: 0.4,
    gravity: 26,
    jumpVelocity: 8.4,
    swimUpVelocity: 4.2,
    reach: 14,
  },
  sky: {
    dayLengthSeconds: 240,
  },
  audio: {
    masterVolume: 0.55,
    footsteps: true,
    spatial: true,
  },
  interaction: {
    repeatDelay: 0.22,
    deformRadius: 2.6,
    deformDepth: 0.42,
  },
};

export const QUALITY_PRESETS = {
  high: {
    shadows: { enabled: true, mapSize: 2048 },
    ssao: { enabled: true },
    bloom: { strength: 0.5 },
    godRays: { enabled: true },
    particles: { motes: 550, fireflies: 150, leaves: 320 },
    grass: { count: 14000 },
    maxPixelRatio: 1.5,
  },
  medium: {
    shadows: { enabled: true, mapSize: 1024 },
    ssao: { enabled: false },
    bloom: { strength: 0.46 },
    godRays: { enabled: true },
    particles: { motes: 280, fireflies: 90, leaves: 160 },
    grass: { count: 7000 },
    maxPixelRatio: 1.25,
  },
  low: {
    shadows: { enabled: false, mapSize: 512 },
    ssao: { enabled: false },
    bloom: { strength: 0.36 },
    godRays: { enabled: false },
    particles: { motes: 120, fireflies: 40, leaves: 80 },
    grass: { count: 2500 },
    maxPixelRatio: 1,
  },
};
